backend:
  name: git-gateway
  branch: master
  repo: https://github.com/Shekey/infinity-hugo-netlify.git
  identity_url: "https://explore-mind.netlify.app/.netlify/identity"
  gateway_url: "https://explore-mind.netlify.app/.netlify/git/github"

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "parts"
    label: "Front page parts"
    label_singular: "part"
    format: yaml-frontmatter
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "hero"
        file: "site/content/hero.md"
        fields:
          - { label: "Site title", name: "site_title", widget: "string" }
          - { label: "Title", name: "title", widget: "text" }
          - { label: "About us title", name: "we_are_who", widget: "string" }
          - { label: "Button text", name: "button_text", widget: "string" }
          - { label: "Sponsor", name: "sponsor_text", widget: "markdown" }
          - {
              label: "Social icons",
              name: "social_icons",
              label_singular: "item",
              widget: "list",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Url", name: "url", widget: "string" },
                ],
            }
      - label: "About us"
        name: "about"
        file: "site/content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "text" }
          - { label: "Subtitle", name: "sutitle", widget: "markdown" }
      - label: "Services"
        name: "services"
        file: "site/content/services.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Big heading", name: "heading", widget: "string" }
          - {
              label: "What we do items",
              name: "items",
              label_singular: "item",
              widget: "list",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Text", name: "text", widget: "string" },
                  { label: "Class", name: "class", widget: "string" },
                ],
            }


